[profile.default]
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
remappings = [
    '@openzeppelin/contracts-upgradeable/proxy/=lib/openzeppelin-contracts-upgradeable/contracts/proxy/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/',
    'solidity-stringutils/=lib/openzeppelin-foundry-upgrades/lib/solidity-stringutils/',
    'ERC4626/=lib/properties/lib/ERC4626/contracts/',
    'properties/=lib/properties/contracts/',
    'redstone-oracles-monorepo/=lib/redstone-oracles-monorepo/',
    '@redstone-finance/=lib/redstone-oracles-monorepo/packages/',
    'solmate/=lib/properties/lib/solmate/src/',
    '@chainlink=lib/chainlink/',
    'chainlink/=lib/chainlink/',
]
deny_warnings = true
ignored_warnings_from = [
    "lib/openzeppelin-contracts-upgradeable/contracts/token/ERC721/ERC721Upgradeable.sol",
]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[fmt]
line_length = 120
multiline_func_header = 'all'
bracket_spacing = true
wrap_comments = true

[invariant]
runs = 50
depth = 50
fail_on_revert = false
