[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
]

[fmt]
line_length = 120
multiline_func_header = 'all'
bracket_spacing = true
wrap_comments = true
