name: PR CI

on:
  pull_request:
    branches: [ main, 'feature/improvements-and-recommendations' ]

permissions:
  contents: read
  security-events: write

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        system:
          - os: macos-12
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
      
    runs-on: ${{ matrix.system.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      #- name: Install Foundry
      #  uses: foundry-rs/foundry-toolchain@v1
      #  with:
      #    version: nightly
        
      - uses: actions/checkout@v4
        with:
         repository: foundry-rs/foundry
         path: ./foundry
         submodules: recursive
         ref: 5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559

      - name: Install Forge
        run: |
         cargo install --path ./foundry/crates/forge --profile local --force --locked      

      - name: Check formatting
        if: ${{ contains(matrix.system.os, 'windows') == false }}
        run: |
          forge fmt --check
        id: formatting

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Slither
        if: ${{ contains(matrix.system.os, 'ubuntu') == true }}
        uses: crytic/slither-action@v0.4.0
        with:
          solc-version: 0.8.23
          sarif: results.sarif
          fail-on: none
          slither-args: --exclude-dependencies --exclude-low --exclude-informational --filter-paths "Ed25519.sol"
        id: slither

      - name: Upload SARIF file
        if: ${{ contains(matrix.system.os, 'ubuntu') == true }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
